#!/usr/bin/env bash
# 1-install_load_balancer
# Install and configure HAproxy on your lb-01 server.
# Configure to send traffic to web-01 and web-02.
# Distribute requests using a roundrobin algorithm
sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
printf %s "frontend haproxy-main
    bind *:80
    option forwardfor
    default_backend nginx_servers

backend nginx_servers
    balance roundrobin
    server 187716-web-01      52.201.222.10:80 check
    server 187716-web-02      34.232.70.226:80 check
" > /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
