#!/usr/bin/env bash
# 1-install_load_balancer
# Install and configure HAproxy on my lb-01 server.
# Configure to send traffic to web-01 and web-02.
# Distribute requests using a roundrobin algorithm

# Update packages
sudo apt update

# Add HAProxy PPA
sudo apt install -y software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt update

# Install HAProxy
sudo apt install -y haproxy=2.0.\*

hgproxy_conf_file="/etc/haproxy/haproxy.cfg"

# Configure Load Balancer
fname="frontend http"
fbind="bind *:80"
fmode="mode http"
fdefault="default_backend web-backend"
frontend="$fname\n\t$fbind\n\t$fmode\n\t$fdefault\n"

bname="backend web-backend"
bbalance="balance roundrobin"
bserver1="server 187716-web-01 52.201.222.10:80 check"
bserver2="server 187716-web-02 34.232.70.226:80 check"
backend="$bname\n\t$bbalance\n\t$bserver1\n\t$bserver2"

sudo sed -i "$ a $frontend" $hgproxy_conf_file
sudo sed -i "$ a $backend" $hgproxy_conf_file

# Restart HAProxy
sudo service haproxy restart
