#!/usr/bin/env bash
# 1-install_load_balancer
# Install and configure HAproxy on my lb-01 server.
# Configure to send traffic to web-01 and web-02.
# Distribute requests using a roundrobin algorithm
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update -y
sudo apt-get install -y haproxy=2.0.\*
echo "ENABLE=1" >> /etc/default/haproxy
printf %s "frontend haproxy-main
    bind *:80
    mode http
    default_backend nginx_servers

backend nginx_servers
    balance roundrobin
    server 187716-web-01 52.201.222.10:80 check
    server 187716-web-02 34.232.70.226:80 check
" > /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
