#!/usr/bin/env bash
# 0-nginx_likes_port_80 
# a Bash script that configures a new Ubuntu machine
sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx
sudo service nginx restart 
