#!/usr/bin/env bash
# 100-read_and_cut - script that displays the content of the file /etc/passwd.
i only displays username, user id and Home directory path for the user
while read -r line; do
  echo "$line" | cut -d ':' -f1,3,6
done < "/etc/passwd"
