#!/usr/bin/env bash
# 4-if_9_say_hi - script that displays Best School 10 times, but for the 9th iteration,
#+ displays Best School and then Hi on a new line.
i="0"

while [ $i -ne 10 ]; do
	echo "Best School"
	if [ $i -eq 8 ]; then
		echo "Hi"
	fi
	i=$((i+1))
done
