#!/usr/bin/env bash
# 0-give_me_a_page
# configures apache2 sever to response with Hello Holberton on port 8080
echo "Hello Holberton" >> /var/www/html/index.html
echo "ServerName localhost" >> /etc/apache2.conf
service apache2 restart
